function getTokenPerfil(){return localStorage.getItem('bloom_token')||sessionStorage.getItem('bloom_token');}
function setUserPerfil(u){ if(localStorage.getItem('bloom_user')) localStorage.setItem('bloom_user', JSON.stringify(u)); else sessionStorage.setItem('bloom_user', JSON.stringify(u)); }
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
async function reqPerfil(endpoint, options={}){const r=await fetch(`http://localhost:5000/api${endpoint}`,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${getTokenPerfil()}`,...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||'Erro na API');return d;}
function msgPerfil(m,t='success'){document.getElementById('perfilMessage').innerHTML=`<div class="alert alert-${t==='error'?'danger':t} rounded-4">${esc(m)}</div>`;}
async function carregarPerfil(){if(!getTokenPerfil()){location.href='login.html?redirect=meu-perfil.html';return;}try{const d=await reqPerfil('/auth/me');const u=d.usuario;['nome','email','telefone','cpf','data_nascimento','genero','endereco','cep','cidade','estado'].forEach(id=>{const el=document.getElementById(id);if(el)el.value=u[id]||'';});document.getElementById('perfilTipo').textContent=u.tipo_usuario||'paciente';}catch(e){msgPerfil(e.message,'error');}}
async function salvarPerfil(e){e.preventDefault();const payload={nome:nome.value,telefone:telefone.value,cpf:cpf.value,data_nascimento:data_nascimento.value||null,genero:genero.value,endereco:endereco.value,cep:cep.value,cidade:cidade.value,estado:estado.value};try{const d=await reqPerfil('/auth/me',{method:'PUT',body:JSON.stringify(payload)});setUserPerfil(d.usuario);msgPerfil('Perfil atualizado com sucesso');}catch(err){msgPerfil(err.message,'error');}}
async function alterarSenha(e){e.preventDefault();try{await reqPerfil('/auth/change-password',{method:'PUT',body:JSON.stringify({senha_atual:senhaAtual.value,nova_senha:novaSenha.value})});senhaAtual.value='';novaSenha.value='';msgPerfil('Senha alterada com sucesso');}catch(err){msgPerfil(err.message,'error');}}
document.addEventListener('DOMContentLoaded',()=>{document.getElementById('perfilForm')?.addEventListener('submit',salvarPerfil);document.getElementById('senhaForm')?.addEventListener('submit',alterarSenha);carregarPerfil();});
